#!/usr/bin/env bash
# A Bash script that transfers a file from our client to a server

if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KE"
	exit 1
fi

path=$1
IP=$2
username=$3
key_path=$4

scp -o StrictHostKEyChecking=no -i $key_path $path $username@$IP:~/
