#!/usr/bin/env bash
# Installing Nginx on my server

sudo pt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Ngnix HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo nginx -t
sudo service nginx restart
