#!/usr/bin/env bash
# Installing Nginx on my server

pt-get -y update
apt-get -y install nginx
ufw allow 'Ngnix HTTP'
service nginx restart
echo "Hello World!" > /var/www/html/index.nginx-debian.html
