#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me
# is redirecting to another page
apt-get -y update
apt-get -y install nginx

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i '/server_name _;/c server_name _;\n\trewrite ^\/redirect_me https:\/\/youtube.com permanent;' /etc/nginx/sites-enabled/default
sudo service nginx restart
