#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header
sudo apt-get update
sudo apt-get -y install nginx
host=$(hostname)
sudo sed -i "/server {/a\ \tadd_header X-Served-By \"$host\";" /etc/nginx/sites-enabled/default
sudo service restart nginx
