#!/usr/bin/env bash
# set up load balancer
balancer_config="\
frontend my_frontend
    bind *:80
    mode http
    default_backend my_backend

backend my_backend
    balance roundrobin
    server 03-web-01 100.25.31.28:80 check
    server 03-web-02 52.91.160.185:80 check
"
# Update packages
sudo apt-get -y update
apt-get -y upgrade
apt-get -y install haproxy

echo "$balancer_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# Enable Haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Testing the HAProxy config file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart the Nginx service
service haproxy restart
