#!/usr/bin/env bash
#Script that stops 4-to_infinity_and_beyond process.

if pgrep -f "4-to_infinity_and_beyond" > /dev/null
then
    pkill -f "4-to_infinity_and_beyond"
    echo "Script '4-to_infinity_and_beyond' has been stopped."
else
    echo "Script '4-to_infinity_and_beyond' is not currently running."
fi
