#!/usr/bin/env bash
# Script displays To infinity and beyond indefinitely with a sleep 2.

sigterm()
{
  echo "I am invincible!!!"
  exit 0
}

trap 'sigterm' SIGTERM

while true; do
  echo "To infinity and beyond indefinitely"
  sleep 2
done
