#!/usr/bin/env bash
#This script displays numbers from 1 to 20 and:
#displays 4 and the bad luck for the for the 4th loop iteration
#displays 9 and then bad luck from Japan for te 9th loop iteration
#displays 17 and then bad luck from italy for the 17th loop iterations

i=1
while [ $i -le 20 ]
do
	echo "$i"

case $i in
	"4")
		echo "bad luck from China"
		;;
	"9")
		echo "bad luck from Japan"
		;;
	"17")
		echo "bad luck from italy"
		;;
esac
	((i++))
done
