#!/usr/bin/env bash
#This script displays content of the current directory in list format
for file in *;
do
    if [[ -f "$file" && "$file" != .* ]]; then
        new_name=$(echo "$file" | cut -d'-' -f2-)
        echo "$new_name"
    fi
done
