#!/usr/bin/env bash
#After connecting to the container and fixing whatever
# needed to be fixed (here is your mission), you can
# see that curling port 80 return a page that contains
# Hello Holberton. Paste the command(s) you used to fix 
#the issue in your answer file.
sudo apt install apache2
sudo service apache2 restart
